pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'cd /var/www/html/blog.nvnhan0810.com'
                sh 'git pull origin main'
                sh 'fnm use'
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'pm2 stop blog-nvnhan0810'
                sh 'pm2 delete blog-nvnhan0810'
                sh 'pm2 --name blog-nvnhan0810 start npm -- start'
            }
        }
    }
}